config/routes.rb
PatentLookup::Application.routes.draw do

  root 'welcome#index'
  match '/about',   to: 'welcome#about',   via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  get "static_pages/tree"
  get "look_result_Septemper.txt"

  resources :lookup
  resources :patents do
    member do
      get 'slice_sentence'
      get 'json_tree', :defaults => { :format => 'json' }
    end
  end
  
  resources :splitwords
  resources :keywordas
  resources :keywordbs
  
  
  
  

end

app/models/splitword.rb
class Splitword < ActiveRecord::Base
end

app/controllers/splitwords_controller.rb
class SplitwordsController < ApplicationController
  
  def index
    @keyworda = Keyworda.where.not('keyworda' => nil).order('priority asc')
    @keywordb = Keywordb.where.not('keywordb' => nil).order('priority asc')
  end
  
  def show 
   
  end
  
  
  def new
    @keyworda = Keyworda.new
    @keywordb = Keywordb.new
  end
  
  def create
    @splitword = Splitword.new(splitword_params)
	
    if @splitword.save
			flash[:success] = "查詢成功!寫入資料庫成功!"
      redirect_to splitwords_path 
		else
			render 'new'
		end
    
  end
 
  def edit
  end
  
  def update
  end
  
  def destroy
    @splitword = Splitword.find(params[:id])
    @splitword.destroy
    redirect_to :action => 'index'
   
  end
  
  private
  
  def splitword_params
    params.require(:splitword).permit(:keyworda, :keywordb)
  
  end
  
  
end

app/helpers/splitwords_helper.rb
module SplitwordsHelper
end

app/views/splitwords/index.html.erb
<h2> 斷詞關鍵字 </h2>   <h2><%= link_to "新增斷詞", new_splitword_path %> </h2>

<div class="row">
  <div class="col-md-6">
<table class="table table-bpatented" id="keywords">
  <thead>
    <tr>
      <th>No. </th>
      <th>keyworda</th>
      <th>優先順序</th>
      <th>調整 </th> 
    </tr>
  </thead>
  <tbody>
    <% @keyworda.each_with_index do |keyword, i| %>
    <tr>
       <td><%= i+1  %></td>
      <td><%=  keyword.keyworda %> </td>
      <td><%=  keyword.priority %> <%= link_to "調整" , edit_keyworda_path(keyword.id) %> </td>
      <td><%= link_to "delete!" , keyworda_path(keyword.id), :method => :delete  %></td> 
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="col-md-6">
<table class="table table-bpatented" id="keywords">
  <thead>
    <tr>
      <th>No. </th>
      <th>keywordb</th>
      <th>優先順序</th>
      <th>調整 </th> 
    </tr>
  </thead>
  <tbody>
    <% @keywordb.each_with_index do |keyword, i| %>
    <tr>
       <td><%= i+1  %></td>
      <td><%=  keyword.keywordb %> </td>
      <td><%=  keyword.priority %> <%= link_to "調整" , edit_keywordb_path(keyword.id) %> </td>
      <td><%= link_to "delete!" , keywordb_path(keyword.id), :method => :delete  %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

app/views/splitwords/new.html.erb
<h1> 增加斷詞組 </h1>

<div class="row">
  <div class="col-md-6">
    <%= render :partial => "keywordas/new", locals: {keyworda: @keyworda} %>
  </div>
   <div class="col-md-6">
    <%= render :partial => "keywordbs/new", locals: {keywordb: @keywordb} %>
  </div>
</div>