config/routes.rb
PatentLookup::Application.routes.draw do

  root 'welcome#index'
  match '/about',   to: 'welcome#about',   via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  get "static_pages/tree"
  get "look_result_Septemper.txt"

  resources :lookup
  resources :patents do
    member do
      get 'slice_sentence'
      get 'json_tree', :defaults => { :format => 'json' }
    end
  end
  
  resources :splitwords
  resources :keywordas
  resources :keywordbs
  
  
  
  

end

app/models/keyworda.rb
class Keyworda < ActiveRecord::Base
  validates :priority, numericality: { only_integer: true }
end

app/controllers/keywordas_controller.rb
class KeywordasController < ApplicationController
   
  def index
    @keywordas = Keyworda.all
  end
  
  def show 

  end
  
  
  def new
    @keyworda = Keyworda.new
  end
  
  def create
    @keyworda = Keyworda.new(keyworda_params)
	
    if @keyworda.save
			flash[:success] = "查詢成功!寫入資料庫成功!"
      redirect_to splitwords_path 
		else
			render 'new'
		end
    
  end
 
  def edit
    @keyworda = Keyworda.find(params[:id])
  end
  
  def update
    @keyworda = Keyworda.find(params[:id])

    if @keyworda.update_attributes(keyworda: params[:keyworda][:keyworda], priority: params[:keyworda][:priority])
    redirect_to splitwords_path
    else 
      puts "error occur"
    end
  end
  
  def destroy
    @keyworda = Keyworda.find(params[:id])
    @keyworda.destroy
    redirect_to splitwords_path
   
  end
  
  private
  
  def keyworda_params
    params.require(:keyworda).permit(:keyworda, :priority)
  
  end
  
  
  
end

app/helpers/keywordas_helper.rb
module KeywordasHelper
end

app/views/keywordas/_new.html.erb
<%= form_for(keyworda, url: keywordas_path) do |f| %>
    <%= f.label :keyworda  %>
    <%= f.text_field :keyworda %>
    <%= f.label :priority %>
    <%= f.number_field :priority %>
    <%= f.submit " 增加第一步斷詞 ", class: "btn btn-large btn-primary" %>
<% end %>

app/views/keywordas/edit.html.erb
<div class="row">
  <div class="col-md-4"> </div>
  <div class="col-md-4"> 
    <%= form_for(@keyworda) do |f| %>
        <%= f.label :keyworda  %>
        <%= f.text_field :keyworda %>
        <%= f.label :priority %>
        <%= f.number_field :priority %>
        <%= f.submit " 更新資料 ", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
   <div class="col-md-4"></div>
</div>