config/routes.rb
PatentLookup::Application.routes.draw do

  root 'welcome#index'
  match '/about',   to: 'welcome#about',   via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  get "static_pages/tree"
  get "look_result_Septemper.txt"

  resources :lookup
  resources :patents do
    member do
      get 'slice_sentence'
      get 'json_tree', :defaults => { :format => 'json' }
    end
  end
  
  resources :splitwords
  resources :keywordas
  resources :keywordbs
  
  
  
  

end

app/models/patent.rb
class Patent < ActiveRecord::Base
  validates_numericality_of :apply_no
  has_many :articles, dependent: :destroy
  #before_save :update_patent_article_total
  
 
	extend FriendlyId
	friendly_id :apply_no, use: :slugged 
	validates(:apply_no, presence: true)


  def self.relationship_parent(patent_scopy)
    
    @parent = Hash.new { |hash,key| hash[:key] =[]}
    independent = Array.new
    d = Array.new
    e = Array.new

   # @patent_scopy_by_item.each do |item|
      patent_scopy.each do |item|
      d.clear
      e.clear
 #     @first_key.each do |match_key| 
 #       if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 ) 

        # 用來抓出從屬項的兩組數字，第一個是自身編號，第二個其繼承的獨立項編號
 #       c = item.scan(/\d+/)
 #       h[:"#{c[1]}"] << [c[0]]       
 #     break
 #       else
          if (item.index("<td class=\"rectd2\">")) == 0 
            d = item.slice(19..item.length).scan(/\d+/)
          else
            d = item.scan(/\d+/)
          end

          # 判斷每一個子項目的母項目編號，寫入陣列當中
                @parent[:"#{d[0]}"] = %w()
            if d.size >= 2 
                @parent[:"#{d[0]}"] << d[1]
            end
         
         
#      end  if ending point
#    end second each loop ending point
         
      end  # each loop ending point
  return @parent
  end  # method relationship_parent ending point


  def self.relationship(patent_scopy)
    
    @h = Hash.new { |hash,key| hash[:key] =[]}
    independent = Array.new
    b = Array.new
    c = Array.new

    patent_scopy.each do |item|
      b.clear
      c.clear
 #     @first_key.each do |match_key| 
 #       if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 ) 

        # 用來抓出從屬項的兩組數字，第一個是自身編號，第二個其繼承的獨立項編號
 #       c = item.scan(/\d+/)
 #       h[:"#{c[1]}"] << [c[0]]       
 #     break
 #       else
          if (item.index("<td class=\"rectd2\">")) == 0 
            b = item.slice(19..item.length).scan(/\d+/)
          else
            b = item.scan(/\d+/)
          end

          # 開始增加獨立項的編號作為 hash 的 key 值 
            @h[:"#{b[0]}"] = %w()
            if b.size >= 2 
              @h[:"#{b[1]}"] << b[0]
            end
          
            independent << b[0]
        #   binding.pry  
  #      end 
  #    end
      independent.uniq
  # Nested set model          
    end
#  binding.pry  
#json = build_tree(@h.keys[0], @h)
  return @h
  end

  def build_tree(id, src)
    child_array = src[:"#{id}"]
  #  @index+=1
    return { name: id } if child_array.empty? 
  #  binding.pry
    #children = child_array
    return { name: id, children: child_array.map { |child_id| build_tree(child_id.to_s, src) } }
  end

# don't know how to use this method
def update_patent_article_total 
  if ( self.patent_scope != "") 
  scopy_by_item = self.patent_scope.split("<br>") 
  self.update_attributes(article_total: scopy_by_item.length) if self.article_total == nil 
  end
end


end
 

app/controllers/patents_controller.rb
class PatentsController < ApplicationController


	def index
    @patents = Patent.all.order("created_at DESC")
	end

	def new

		@patent = Patent.new

	end

	def create
		@patent = Patent.new(patent_params)
		return_patent_scope(patent_params[:apply_no],12)
		@patent.patent_scope = @result

		if @patent.save
			#flash[:success] = "查詢成功!寫入資料庫成功!"
			redirect_to @patent
		else
			render 'new'
		end

	end

  def slice_sentence
    @patent = Patent.friendly.find(params[:id])
		@patent_scopy_by_item = @patent.patent_scope.split("<br>")
    index = 0
    b = Array.new
    c = Array.new

    @patent_scopy_by_item.each do |item|
     # binding.pry
      article = Article.new
      article.patent_id = params[:id].to_s
      #article.sentence_id = index+1
      article.sentence = item

      b.clear
      c.clear
          if (item.index("<td class=\"rectd2\">")) == 0
            b = item.slice(19..item.length).scan(/\d+/)
          else
            b = item.scan(/\d+/)
          end

         # binding.pry

          if b.size >=2
            article.child_id = b[0]
            article.parent_id = b[1]
            article.sentence_id = b[0]
          else
            article.child_id = "no_child"
            article.parent_id = "no_parent"
            article.sentence_id = b[0]
          end

      if article.save
      #  flash[:success] = "查詢成功!寫入資料庫成功!"
      #  redirect_to :back
      else
        puts "error occur"
      end
	  end
    redirect_to @patent

  end

  def json_tree
    @patent = Patent.friendly.find(params[:id])
		@patent_scopy_by_item = @patent.patent_scope.split("<br>")

    @abc = Patent.relationship_parent(@patent_scopy_by_item)
    @def = Patent.relationship(@patent_scopy_by_item)
   # binding.pry
    @show_index = @abc.select {|k,v| v.empty? }

    @result_hash = []
      @show_index.keys.each do |root|
     # binding.pry
      @result_hash << build_tree(root.to_s, @def)
     # binding.pry
      end

    respond_to do |format|
      format.json { render json: @result_hash.to_json  }
    end
  end


	def show

	#	@patent = Patent.find(params[:id])
	#   use friendly_id as slugged title
		@patent = Patent.friendly.find(params[:id])
		@patent_scopy_by_item = @patent.patent_scope.split("<br>")
    if @patent.patent_scope.include? "<a href="
      render :template => "patents/manual"
    else
      @first_key = Keyworda.where.not('keyworda' => nil).order('priority asc').pluck(:keyworda)
      @second_key = Keywordb.where.not('keywordb' => nil).order('priority asc').pluck(:keywordb)
      @patent_scopy_by_item_right = Array.new
      @repeat_no = Array.new(1,"No.0")
      @patent.update_attributes(article_total: @patent_scopy_by_item.length) if @patent.article_total == nil
    end
	end

	def edit

		#@patent = Patent.find(params[:id])
		@patent = Patent.friendly.find(params[:id])
		@patent_scopy_by_item = @patent.patent_scope.split("<br>")

	end

	def update

		@patent = Patent.friendly.find(params[:id])
		return_patent_scope(params[:apply_no],params[:new_fetch_no])

		if @patent.update_attributes(patent_scope: @result)
		redirect_to @patent
		else
			puts "error occur"
		end

	end


   def destroy
     @patent = Patent.friendly.find(params[:id])
     @patent.destroy
     redirect_to patents_path, alert: "此申請案查詢已刪除"
   end

def return_patent_scope(apply_key,fetch_key)
		require 'rubygems'
		require 'nokogiri'
		#require 'open-uri'
		#require 'watir-webdriver'
		require 'mechanize'

		agent = Mechanize.new
		page = agent.get("http://210.69.13.42/tipotwoc/tipotwkm")
		#page = agent.get("http://twpat.tipo.gov.tw/tipotwoc/tipotwkm")
		page = agent.page.link_with(:text => "簡易檢索").click
		form = agent.page.forms.first
		#設定下拉式選單到正確的選項 value
		form._1_0_n_1 = "n_AN"
		#設定 input box 裡面要查詢的值
		#form._1_0_n_2 = "99106886"
		form._1_0_n_2 = "#{apply_key}"
		#按下查詢的按鈕
		result_page = form.submit(form.button_with(:name => "_IMG_檢索@s"))

		#按下“專利範圍”的連結

	if !(result_page.links_with(:text => "")[3].href.match(/^http:\/\/twpat/) )
			@result = "查無此專利案"
	else
		result_page2 = result_page.links_with(:text => "")[2].click
		page_html = Nokogiri::HTML.parse(result_page2.parser.to_html)

     while fetch_key.to_i >=0 do
	   @result = page_html.xpath("/html/body/form/table/tr/td/table/tr[3]/td/table/tr/td/table/tr[3]/td/table/tr/td/table/tr[2]/td/table/tr/td[1]/div/table/tr[#{fetch_key}]/td[2]").to_s
      #binding.pry
      if @result == ""
        fetch_key -= 1
      else
        break
      end  # if statement end
     end   # while loop end
  end # if statement end
  # binding.pry

end # method end



	private

	def patent_params
    params.require(:patent).permit(:apply_no, :patent_scope)
  end


  def build_tree(id, src)
    child_array = src[:"#{id}"]
  #  @index+=1
    return { "name" => id } if child_array.empty?
  #  binding.pry
    #children = child_array
    return { "name" => id, "children" => child_array.map { |child_id| build_tree(child_id.to_s, src) } }
  end


end

app/helpers/patents_helper.rb
module PatentsHelper

	def right_slice(item)
   # @patent_scopy_by_item_right = Array.new
    @second_scope = ""
    @first_key.each do |match_key|
      if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 )
          @second_key.each do |match_key2|
            if (item.index("#{match_key2}")) != nil
            # 計算要從斷詞開始往右邊取到最後停止
              temp_right = item.slice( (item.index("#{match_key2}").to_i+match_key2.length)..(item.size) )
              if temp_right.match("</td>") != nil
                @second_scope = temp_right.slice(0..(temp_right.length-6))
              else
                @second_scope = temp_right
              end
            break
            else
              @seconde_scope = "此項目為附屬項，但第二步關鍵字比對不到"
            end
          end
      break
      else
         @second_scope= ""
      end

    end
        @patent_scopy_by_item_right << @second_scope
        @repeat_no << (@patent_scopy_by_item_right.index("#{@second_scope}")+1)
  return @second_scope
    #  binding.pry
  end

  def left_slice(item)
    @first_key.each do |match_key| item
      if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 )
          @second_key.each do |match_key2|
            if (item.index("#{match_key2}")) != nil
            # 計算要從第一個字往右邊取到何時停止
              @first_scope= item.slice( 1..(item.index("#{match_key2}").to_i+(match_key2.length-1) ) )
            break
            else
              @first_scope = "此項目為附屬項，但第二步關鍵字比對不到"
            end
          end
      break
      else
          #@first_scope= item
          if (item.index("<td class=\"rectd2\">")) == 0
            temp_left = item.slice(19..item.length)
              if temp_left.match("</td>") != nil
                @first_scope = temp_left.slice(0..(temp_left.length-6))
              else
                @first_scope = temp_left
              end
          else
              if item.match("</td>") != nil
                @first_scope = item.slice(0..(item.length-6))
              else
                @first_scope = item
              end
          end
      end
    #  binding.pry
    end
  return @first_scope
  end

  def column_color(item)
    @first_key.each do |match_key|
      if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 )
       @color = ""
      break
      else
       @color = "red"
      end
    end
  return @color
  end

  def relationship

    @h = Hash.new { |hash,key| hash[key] =[]}
    independent = Array.new
    b = Array.new
    c = Array.new

    #binding.pry

    @patent_scopy_by_item.each do |item|
      b.clear
      c.clear
 #     @first_key.each do |match_key|
 #       if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 )

        # 用來抓出從屬項的兩組數i字，第一個是自身編號，第二個其繼承的獨立項編號
 #       c = item.scan(/\d+/)
 #       h[:"#{c[1]}"] << [c[0]]
 #     break
 #       else
          if (item.index("<td class=\"rectd2\">")) == 0
            b = item.slice(19..item.length).scan(/\d+/)
          else
            b = item.scan(/\d+/)
          end

          # 開始增加獨立項的編號作為 hash 的 key 值
            if b.size >= 2
              @h[:"#{b[1]}"] << b[0]
            end

            independent << b[0]
  #         binding.pry
  #      end
  #    end
      independent.uniq
  # Nested set model
    end
 # binding.pry
#json = build_tree(@h.keys[0], @h)
  end

  def build_entire_tree(first_key, h)

  end


  def build_tree(id, src)
    child_array = src[:"#{id}"]
  #  @index+=1
    return { name: id } if child_array.empty?
  #  binding.pry
    #children = child_array
    { name: id, children: child_array.map { |child_id| build_tree(child_id.to_s, src) } }
  end



def relationship_parent

    @parent = Hash.new { |hash,key| hash[:key] =[]}
    independent = Array.new
    d = Array.new
    e = Array.new

    @patent_scopy_by_item.each do |item|
      d.clear
      e.clear
 #     @first_key.each do |match_key|
 #       if ( item.index("#{match_key}") == 3 ) || ( item.index("#{match_key}") == 4 )

        # 用來抓出從屬項的兩組數字，第一個是自身編號，第二個其繼承的獨立項編號
 #       c = item.scan(/\d+/)
 #       h[:"#{c[1]}"] << [c[0]]
 #     break
 #       else
          if (item.index("<td class=\"rectd2\">")) == 0
            d = item.slice(19..item.length).scan(/\d+/)
          else
            d = item.scan(/\d+/)
          end

          # 判斷每一個子項目的母項目編號，寫入陣列當中
                @parent[:"#{d[0]}"] = %w()
            if d.size >= 2
                @parent[:"#{d[0]}"] << d[1]
            end
         #  binding.pry



#      end  if ending point
#    end second each loop ending point

      end  # each loop ending point
#  binding.pry
  end  # method ending point


end   # helper module ending point

app/views/patents/edit.html.erb
<h1>Update your fetch 的格子數</h1>

目前正常的專利範圍是在第 12 格 <br> 
如果看到抓回來的資料是在專利範圍的下一格，請在下方格子輸入  11  按下送出重新抓取一次  <br>

<div class="row">
  <div class="span6 offset3">
    <%= form_tag patent_path(@patent), method: "patch" do %>
	<% puts "New column NO:"  %> 
      
      <%= text_field_tag "apply_no", @patent.apply_no %>
      <%= text_field_tag "new_fetch_no" %> 
    
      <%= submit_tag "送出更新", class: "btn btn-large btn-primary" %>
    <% end %>

app/views/patents/index.html.erb
<h2>查詢記錄 </h2>

<table class="table table-bpatented" id="patents">
  <thead>
    <tr>
      <th>No. </th>
      <th>申請號</th>
      <th>生成時間</th>
    </tr>
  </thead>
  <tbody>
    <% @patents.each_with_index do |patent, i| %>
    <tr>
       <td><%= i+1  %></td>
      <td><%= link_to(patent.apply_no, patent) %>  <span class="badge alert-info"><%= patent.article_total %> </span></td>
       <td><%= patent.created_at %> </td>
      <td><%= link_to( "句子寫進資料庫", slice_sentence_patent_path(patent)) %> </td>
      <td><%= link_to( "切Json file" , json_tree_patent_path(patent) )  %> </td> 
      <td><%= link_to("Delete", patent_path(patent), method: :delete, data: { confirm: "Are you sure?" } )%>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/patents/json_tree.html.erb
    <script>  
      
    var width = 500,  
    height = 500;  
      
    var tree = d3.layout.tree()  
        .size([width, height-200])  
        .separation(function(a, b) { return (a.parent == b.parent ? 1 : 2) / a.depth; });  
      
    var diagonal = d3.svg.diagonal()  
        .projection(function(d) { return [d.y, d.x]; });  
      
    var svg = d3.select("body").append("svg")  
        .attr("width", width)  
        .attr("height", height)  
        .append("g")  
        .attr("transform", "translate(40,0)");  
      
      
      
    d3.json("json_tree", function(error, root) {  
      
        var nodes = tree.nodes(root);  
        var links = tree.links(nodes);  
          
        console.log(nodes);  
        console.log(links);  
          
        var link = svg.selectAll(".link")  
          .data(links)  
          .enter()  
          .append("path")  
          .attr("class", "link")  
          .attr("d", diagonal);  
          
        var node = svg.selectAll(".node")  
          .data(nodes)  
          .enter()  
          .append("g")  
          .attr("class", "node")  
          .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })  
          
        node.append("circle")  
          .attr("r", 4.5);  
          
        node.append("text")  
          .attr("dx", function(d) { return d.children ? -8 : 8; })  
          .attr("dy", 3)  
          .style("text-anchor", function(d) { return d.children ? "end" : "start"; })  
          .text(function(d) { return d.name; });  
        });  
      
    </script>  
 

app/views/patents/manual.html.erb
<h1>專利範圍內包含額外的 LINK 字串，系統無法處理<br>請回專利資訊檢索系統人工處理</h1> 
<div align='center'><%= link_to "中華民國專利資訊檢索系統", 'http://210.69.13.199/tipotwc/tipotwkm?0002A9C60001000100000000000000100000001E000000000', :target => "_blank" %></div><br>
<li><%= link_to "繼續查下一筆", new_patent_path %></li>   <li><%= link_to "去歷史查詢列表", patents_path %> </li>
<li><%= link_to "編輯這一筆查詢，調整fetch的格子數" , edit_patent_path %></li> 
<table>
	<tr> 
		<td> 申請號 </td> <td><%= @patent.apply_no %></td>
	</tr>
	<tr>
		<td>專利範圍</td> <td> </td>
	</tr>
</table>
<ul class ="users"> 
<% @patent_scopy_by_item.each do |scope_item| %>
  <li>
  <%= scope_item  %> 
</li>
<% end %>

app/views/patents/new.html.erb
<h1> this is the new lookup page </h1>
<% if @patent.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@patent.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @patent.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <div class="col-md-4"> </div>
  <div class="col-md-4">
 
    <%= form_for(@patent) do |f| %>
 
      <%= f.label :apply_no %>
      <%= f.text_field :apply_no %>

      <%= f.submit "Go to Find it !! ", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
   <div class="col-md-4"></div>
</div>

app/views/patents/show.html.erb
<h1>專利申請案號: <%= @patent.apply_no %>  專利範圍 </h1> <br>
<li><%= link_to "繼續查下一筆", new_patent_path %></li>   <li><%= link_to "去歷史查詢列表", patents_path %> </li>
<li><%= link_to "編輯這一筆查詢，調整fetch的格子數" , edit_patent_path %></li> 
<table>
	<tr> 
		<td> 申請號 </td> <td><%= @patent.apply_no %></td>
	</tr>
	<tr>
		<td>專利範圍原始資料</td> <td> </td>
	</tr>
</table>
 <% relationship_parent %>
<ul class ="users"> 
<% @patent_scopy_by_item.each do |scope_item| %>
  <li>
  <%= scope_item  %> 
</li>
<% end %>

<hr>
<table class='table-bordered table-hover' >
<tr>
	<td class="col-md-6"> 主要項內容 </td>
	<td class="col-md-6"> 附屬項內容 </td>
</tr>
	<% @patent_scopy_by_item.each do |item| %>
	<tr class="<%= column_color(item) %>">
		<td class='<%= column_color(item) %>'><font color='<%= column_color(item) %>'><%= left_slice(item)  %></td>
		<td><%= right_slice(item) %></td>
	</tr>
	<% end %>
</table>
<hr>
  <% relationship %>
  <%#  binding.pry %> 
<div class="row">
  <div class="col-md-4">

<table class='table-bordered'>
<tr>
  <td>請求項編號 </td>
  <td>此項目下，子附屬項編號LIST </td>
</tr>
<tr>
  <% @h.each do |key,value| %> 
  <td><%= key %> </td>
  <td><%= value.join(",") %></td>
</tr>
  <% end %> 

</table> 
</div>
<div class="col-md-2">  
<table class='table-bordered'>
<tr>
  <td>請求項編號 </td>
  <td>Parent Node No. </td>
  
</tr>
<tr>
  <% @parent.each do |key,value| %> 
  <td><%= key %> </td>
  <td><%= value.join("") %></td>
</tr>
  <% end %>
</table> 
 
  
</div>
<div class="col-md-2">
   <table class='table-bordered'>
    <tr>
      <td> 請求項編號  </td>
    <td>與前面項目，第一次重複的編號 </td>
    </tr>
    <tr>
      <% @repeat_no.from(1).each_with_index do |repeat_no , index| %> 
      <% if index+1 !=repeat_no && repeat_no != 1 %> 
      <td><%= index+1 %> </td>
      <td><%= repeat_no %></td>
       </tr> 
       <% end %>
      <% end %> 
  </table> 
</div>
<div class="col-md-4">
</div>
</ul> 

<br> 
    <div>
      <hr>
      <% @show_index = @parent.select {|k,v| v.empty? } %>
      <% @show_index.keys.each do |root| %> 
      <%= build_tree(root.to_s, @h) %>
      <br>
      <br>
      <% end %>
      
      <%# build_entire_tree(@h.keys[0].to_s, @h) %>
    </div>
<br>
<hr>
  
<script type="text/javascript"> 
var treeData;
$.ajax({  
 //url: '97146873/json_tree', 
 url: '<%= "#{params[:id]}/json_tree" %>',
  type: 'GET',
  dataType: 'json',
  async: false, 
      success: function(datajson) {
      //console.log(datajson)
        treeData = datajson ;

      },
      error: function(datajson) {
      alert ("糟糕啊！！");
      }  
  });

// ************** Generate the tree diagram  *****************
  var root_index = 0 ;
  var root_total_number = treeData.length ;


var margin = {top: 20, right: 120, bottom: 20, left: 120},
  width = 1300 - margin.right - margin.left,
  height =1000 - margin.top - margin.bottom;

for(root_index;root_index<root_total_number;root_index++){  
var i = 0,
  duration = 750,
  root;

var tree = d3.layout.tree()
  .size([height, width]);

var diagonal = d3.svg.diagonal()
  .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("body").append("svg")
  .attr("width", width + margin.right + margin.left)
  .attr("height", height + margin.top + margin.bottom)
  .append("g")
  .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

root = treeData[root_index];
root.x0 = height / 2;
root.y0 = 0;
  
update(root);

d3.select(self.frameElement).style("height", "1000px");

function update(source) {

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
    links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d) { d.y = d.depth * 180; });

  // Update the nodes…
  var node = svg.selectAll("g.node")
    .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
    .attr("class", "node")
    .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
    .on("click", click);

  nodeEnter.append("circle")
    .attr("r", 1e-6)
    .style("fill", function(d) { return d._children ? "lightsteelblue" : "#fff"; });

  nodeEnter.append("text")
    .attr("x", function(d) { return d.children || d._children ? -13 : 13; })
    .attr("dy", ".35em")
    .attr("text-anchor", function(d) { return d.children || d._children ? "end" : "start"; })
    .text(function(d) { return d.name; })
    .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
    .duration(duration)
    .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
    .attr("r", 10)
    .style("fill", function(d) { return d._children ? "lightsteelblue" : "#fff"; });

  nodeUpdate.select("text")
    .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position.
  var nodeExit = node.exit().transition()
    .duration(duration)
    .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
    .remove();

  nodeExit.select("circle")
    .attr("r", 1e-6);

  nodeExit.select("text")
    .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
    .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position.
  link.enter().insert("path", "g")
    .attr("class", "link")
    .attr("d", function(d) {
    var o = {x: source.x0, y: source.y0};
    return diagonal({source: o, target: o});
    });

  // Transition links to their new position.
  link.transition()
    .duration(duration)
    .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position.
  link.exit().transition()
    .duration(duration)
    .attr("d", function(d) {
    var o = {x: source.x, y: source.y};
    return diagonal({source: o, target: o});
    })
    .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
  d.x0 = d.x;
  d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {
  if (d.children) {
  d._children = d.children;
  d.children = null;
  } else {
  d.children = d._children;
  d._children = null;
  }
  update(d);
}
  }
</script>

 