config/routes.rb
PatentLookup::Application.routes.draw do

  root 'welcome#index'
  match '/about',   to: 'welcome#about',   via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  get "static_pages/tree"
  get "look_result_Septemper.txt"

  resources :lookup
  resources :patents do
    member do
      get 'slice_sentence'
      get 'json_tree', :defaults => { :format => 'json' }
    end
  end
  
  resources :splitwords
  resources :keywordas
  resources :keywordbs
  
  
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Patent Lookup Site </a>
    by Daniel Lin
<%= link_to "中華民國專利資訊檢索系統", 'http://210.69.13.199/tipotwc/tipotwkm?0002A9C60001000100000000000000100000001E000000000', :target => "_blank" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Patent_Lookup</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "斷詞關鍵字一覽表", splitwords_path %></li>          
        <li><%= link_to "申請號查詢頁面",    new_patent_path %></li>
        <li><%= link_to "去歷史查詢列表", patents_path %> </li>
        <li><%= link_to "Sign in", '#' %></li>
      </ul>
    </div>
  </div>
</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatentLookup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

    <style>
  
  .node {
    cursor: pointer;
  }

  .node circle {
    fill: #fff;
    stroke: steelblue;
    stroke-width: 3px;
  }

  .node text {
    font: 12px sans-serif;
  }

  .link {
    fill: none;
    stroke: #ccc;
    stroke-width: 2px;
  }
  
    </style>


</head>
<body>
 

	<%= render 'layouts/header' %> 

    <div class="container">
      <%= yield %>
    </div>

	<%= render 'layouts/footer' %> 
	<%= debug(params) if Rails.env.development? %>
</body>
</html>